### ISSUE TITLE
Acces to subcomponents

### ISSUE THREAD

**Issue by mamatt** [nextcloud/nextcloud-vue-collections#593]
Collections are a great way to handle projects in Nextcloud.  
However it's missing a "place" to view all  projects.

I'm writing a App for that, but the nextcloud-vue-collections component is not giving acces to the collectionListitem sub component which should be handy to list collections.

You should just modify the index.js to export the collectionListItem.

I can make a PR for that of course, but this is so simple ;)

**Comment by juliushaertl** [comment]
Done with https://github.com/nextcloud/nextcloud-vue-collections/commit/5fab05387710bd9ab5ff2dd214b667c30cb08679
